pipeline {
    agent any
    stages {
        stage("build the project") {
            steps {
                dir('pet_clinic') {
                    sh "mvn clean package"
                }
            }
        }
        stage("stop previous running container") {
            steps {
                dir('pet_clinic') {
                    sh "docker-compose down"
                }
            }
        }
        stage("run the docker container") {
            steps {
                dir('pet_clinic') {
                    sh "docker-compose up --build -d"
                }
            }
        }
    }
}
